sosw/app.py

If we have several classes, and each inherits from processor - I want to know who the final config belongs to.

Print class name for final config

---

Pipfile
Pipfile.lock
docs/contribution.rst
docs/greenfield.rst
docs/index.rst
docs/installation.rst
sosw/app.py
sosw/managers/task.py

- Add installation rst
- Add pipenv setup

Documentation Updates

---

README.md

updated README with more detail

---

sosw/managers/ecology.py
sosw/managers/test/unit/test_ecology.py

Max labourer duration

---

README.md
docs/orchestrator.rst
sosw/components/helpers.py
sosw/components/test/unit/test_helpers.py
sosw/labourer.py
sosw/managers/ecology.py
sosw/managers/task.py
sosw/managers/test/unit/test_ecology.py
sosw/managers/test/unit/test_task.py

Ecology Manager supports health status based on configurable metrics per Labourer
Fix #72

Labourer health

---

sosw/components/dynamo_db.py
sosw/components/siblings.py
sosw/components/test/integration/test_dynamo_db_i.py
sosw/components/test/unit/test_dynamo_db.py

Map type is for jsons / dictionaries.

Dynamo map type

---

sosw/components/sns.py
sosw/components/test/unit/test_sns.py

- create_topic()
- subscribe()

wrappers for SNS are added

---

sosw/components/dynamo_db.py
sosw/components/test/integration/test_dynamo_db_i.py
sosw/components/test/unit/test_dynamo_db.py

Remove attributes from a record

Dynamo client - remove attribute

---

sosw/components/sns.py

new separator for queue messages setter

---

sosw/components/dynamo_db.py
sosw/components/test/integration/test_dynamo_db_i.py
sosw/components/test/unit/test_dynamo_db.py

get_query method receive ExpressionAttributeNames

get_query method receive ExpressionAttributeNames

---

sosw/managers/task.py
sosw/managers/test/integration/test_task_i.py
sosw/worker_assistant.py

Need it to transfer ALL fields from `sosw_tasks` to `sosw_closed_tasks`

WorkerAssistant + TaskManager updates

---

sosw/components/helpers.py
sosw/components/test/unit/test_helpers.py

helpers.recursive_update: Now supports merging lists of Dictionaries preserving unique

helpers.recursive_update: merging lists of Dictionaries

---

docs/managers/meta_handler.rst
sosw/components/dynamo_db.py
sosw/components/helpers.py
sosw/components/test/integration/test_dynamo_db_i.py
sosw/components/test/unit/test_dynamo_db.py
sosw/managers/meta_handler.py
sosw/worker.py

- dynamo_db: create - docs and tests
- meta_handler: fix default config
- meta_handler: more docs
- worker: cautious support for MetaHandler

MetaHandler

---

sosw/components/dynamo_db.py
sosw/components/test/unit/test_dynamo_db.py

Unexpected type in DDB - raise the right exception

---

docs/contribution/convention.rst
sosw/components/decorators.py
sosw/components/dynamo_db.py
sosw/components/test/unit/test_dynamo_db.py

Get capacity returns a healthy None (same as DynamoDB API does from AWS).

DynamoDB support for on demand tables

---

sosw/scheduler.py
sosw/test/unit/test_scheduler.py

This method will be called on init and during every call where the job schema is changed.

Moved intialization of chunkable_attrs to their own method. 

---

README.md
sosw/components/helpers.py

Added examples for recursive_update documentation and fixed link to documentation (README.md)

Added examples for recursive_update documentation and fixed link to documentation

---

docs/components/index.rst
docs/components/sigv4.rst
sosw/components/sigv4.py
sosw/components/test/unit/test_sigv4.py
sosw/test/suite_unit.py

Signature Version 4 (SigV4) is the process to add authentication information to AWS API requests sent by HTTP.
For security, most requests to AWS must be signed with an access key. The access key consists of an access key
ID and secret access key, which are commonly referred to as your security credentials.
How Signature Version 4 works:
1. Create a canonical request.
2. Use the canonical request and additional metadata to create a string for signing.
3. Derive a signing key from your AWS secret access key. Then use the signing key, and the string from the previous
step, to create a signature.
4. Add the resulting signature to the HTTP request in a header

AWS sigv4 component

---

sosw/components/helpers.py
sosw/components/test/unit/test_helpers.py

created tests and updated mutators for recognizing string with timestamps both seconds and floats

upgraded function validate_date_from_smth 

---

sosw/components/dynamo_db.py

DDB doc styling

---

sosw/components/config.py
sosw/components/test/test_config.py

Fix config

---

.coveragerc
Pipfile
Pipfile.lock
docs/_static/images/coverage.svg
docs/contribution/index.rst
docs/index.rst
pyproject.toml
sosw/components/helpers.py
sosw/components/test/unit/test_helpers.py

- [recursive_insert: test_recursive_insert](https://github.com/sosw/sosw/commit/2bfbbed5bd6212c191863f623444d659555f0f4b)
- [Added Coverage calculating tools and badge](https://github.com/sosw/sosw/commit/cc917c934c0fd92eb9ab7bedafbdd2cd5a721c67)

`recursive_insert` helper

---

sosw/app.py
sosw/components/helpers.py
sosw/test/unit/test_app.py

Recursively access elements in config.
Fix #342

_c helper in app.py

---

sosw/app.py

declared Processor class variables for stats and result
FIX #344

declared Processor class variables for stats and result

---

sosw/components/helpers.py
sosw/components/test/unit/test_helpers.py

https://github.com/sosw/sosw/issues/356

slug_to_camel_case
